-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 16:05:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 15:49:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SportsDB
-- The 3 lines below are mandatory in your databasemodel.sql but of course, with your database name.
-- -----------------------------------------------------
DROP DATABASE IF EXISTS SportsDB;
CREATE DATABASE IF NOT EXISTS SportsDB;
USE SportsDB;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Personal Details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Player` ;

CREATE TABLE IF NOT EXISTS `Player` (
  `PlayerID` INT NOT NULL,
  `Leave Requests` VARCHAR(45) NOT NULL,
  `Performance Stats` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PlayerID`),
  CONSTRAINT `UserID`
    FOREIGN KEY (`PlayerID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Coach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coach` ;

CREATE TABLE IF NOT EXISTS `Coach` (
  `CoachID` INT NOT NULL AUTO_INCREMENT,
  `Training Programs Assigned` VARCHAR(45) NOT NULL,
  `Team Schedule` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CoachID`),
    FOREIGN KEY (`CoachID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team` ;

CREATE TABLE IF NOT EXISTS `Team` (
  `TeamID` INT NOT NULL AUTO_INCREMENT,
  `Roster` VARCHAR(45) NOT NULL,
  `Historical Performance Data` VARCHAR(45) NOT NULL,
  `Attendance Tracking` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TeamID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scheduler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scheduler` ;

CREATE TABLE IF NOT EXISTS `Scheduler` (
  `SchedulerID` INT NOT NULL,
  `Notifications` VARCHAR(45) NOT NULL,
  `Referee Allocation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SchedulerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Referee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Referee` ;

CREATE TABLE IF NOT EXISTS `Referee` (
  `RefereeID` INT NOT NULL AUTO_INCREMENT,
  `Game Scores Entered` VARCHAR(45) NOT NULL,
  `Disciplinary Actions` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RefereeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Parent` ;

CREATE TABLE IF NOT EXISTS `Parent` (
  `ParentID` INT NOT NULL AUTO_INCREMENT,
  `Child's Game Schedule Access` VARCHAR(45) NOT NULL,
  `Notifications` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ParentID`),
    FOREIGN KEY (`ParentID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medical Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medical Staff` ;

CREATE TABLE IF NOT EXISTS `Medical Staff` (
  `Medical StaffID` INT NOT NULL,
  `Contact Info` VARCHAR(45) NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Health Records` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Medical StaffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `System Administrator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `System Administrator` ;

CREATE TABLE IF NOT EXISTS `System Administrator` (
  `AdminID` INT NOT NULL AUTO_INCREMENT,
  `Access Level` VARCHAR(45) NOT NULL,
  `Contact Info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminID`),
    FOREIGN KEY (`AdminID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Financial Officer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Financial Officer` ;

CREATE TABLE IF NOT EXISTS `Financial Officer` (
  `FinancialOfficerID` INT NOT NULL AUTO_INCREMENT,
  `Access To Financial Reports` VARCHAR(45) NOT NULL,
  `Budget Management` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FinancialOfficerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Merchandise Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merchandise Manager` ;

CREATE TABLE IF NOT EXISTS `Merchandise Manager` (
  `MerchManagerID` INT NOT NULL AUTO_INCREMENT,
  `Inventory Management` VARCHAR(45) NOT NULL,
  `Sales Report` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MerchManagerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sports League Organizer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sports League Organizer` ;

CREATE TABLE IF NOT EXISTS `Sports League Organizer` (
  `OrganizerID` INT NOT NULL AUTO_INCREMENT,
  `League Schedule` VARCHAR(45) NOT NULL,
  `Contact Info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrganizerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game Statistics Provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game Statistics Provider` ;

CREATE TABLE IF NOT EXISTS `Game Statistics Provider` (
  `ProviderID` INT NOT NULL AUTO_INCREMENT,
  `Data Accuracy` VARCHAR(45) NOT NULL,
  `Reliability` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProviderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Social Media Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Social Media Manager` ;

CREATE TABLE IF NOT EXISTS `Social Media Manager` (
  `SocialMediaManagerID` INT NOT NULL AUTO_INCREMENT,
  `Platform Expertise` VARCHAR(45) NOT NULL,
  `Engagement Analytics` VARCHAR(45) NOT NULL,
  `Notifications Sent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SocialMediaManagerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fan/User Watching the Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fan/User Watching the Game` ;

CREATE TABLE IF NOT EXISTS `Fan/User Watching the Game` (
  `FanID` INT NOT NULL AUTO_INCREMENT,
  `Subscription Details` VARCHAR(45) NOT NULL,
  `Preferences` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FanID`),
    FOREIGN KEY (`FanID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fan/User Interacting with Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fan/User Interacting with Players` ;

CREATE TABLE IF NOT EXISTS `Fan/User Interacting with Players` (
  `InteractingFanID` INT NOT NULL AUTO_INCREMENT,
  `Interaction History` VARCHAR(45) NOT NULL,
  `Preferences` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`InteractingFanID`),
    FOREIGN KEY (`InteractingFanID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fan/User Reviewing Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fan/User Reviewing Games` ;

CREATE TABLE IF NOT EXISTS `Fan/User Reviewing Games` (
  `ReviewingFanID` INT NOT NULL AUTO_INCREMENT,
  `Review History` VARCHAR(45) NOT NULL,
  `Feedback` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ReviewingFanID`),
    FOREIGN KEY (`ReviewingFanID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team Staff` ;

CREATE TABLE IF NOT EXISTS `Team Staff` (
  `TeamStaffID` INT NOT NULL,
  `Role Description` VARCHAR(45) NOT NULL,
  `Contact Info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TeamStaffID`),
    FOREIGN KEY (`TeamStaffID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team Captain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team Captain` ;

CREATE TABLE IF NOT EXISTS `Team Captain` (
  `Team Captain ID` INT NOT NULL,
  `Leadership Role` VARCHAR(45) NOT NULL,
  `Strategy Input` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Team Captain ID`),
    FOREIGN KEY (`Team Captain ID`)
    REFERENCES `User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Scout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Scout` ;

CREATE TABLE IF NOT EXISTS `Scout` (
  `ScoutID` INT NOT NULL,
  `Recruitment Focus` VARCHAR(45) NOT NULL,
  `Contact Info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ScoutID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Player Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Player Agent` ;

CREATE TABLE IF NOT EXISTS `Player Agent` (
  `AgentID` INT NOT NULL,
  `Client List` VARCHAR(45) NOT NULL,
  `Negotiation Skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AgentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayerFanUserInteractingwithPlayersAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayerFanUserInteractingwithPlayersAssociation` ;

CREATE TABLE IF NOT EXISTS `PlayerFanUserInteractingwithPlayersAssociation` (
  `PlayerID` INT NOT NULL,
  `InteractingFanID` INT NOT NULL,
  INDEX `PlayerID_idx` (`PlayerID` ASC) VISIBLE,
  INDEX `InteractingFanID_idx` (`InteractingFanID` ASC) VISIBLE,
  CONSTRAINT `PlayerID`
    FOREIGN KEY (`PlayerID`)
    REFERENCES `Player` (`PlayerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InteractingFanID`
    FOREIGN KEY (`InteractingFanID`)
    REFERENCES `Fan/User Interacting with Players` (`InteractingFanID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayerPlayerAgentAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayerPlayerAgentAssociation` ;

CREATE TABLE IF NOT EXISTS `PlayerPlayerAgentAssociation` (
  `PlayerID` INT NOT NULL,
  `AgentID` INT NOT NULL,
  INDEX `PlayerID_idx` (`PlayerID` ASC) VISIBLE,
  INDEX `AgentID_idx` (`AgentID` ASC) VISIBLE,
    FOREIGN KEY (`PlayerID`)
    REFERENCES `Player` (`PlayerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AgentID`
    FOREIGN KEY (`AgentID`)
    REFERENCES `Player Agent` (`AgentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayerMedicalStaffAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayerMedicalStaffAssociation` ;

CREATE TABLE IF NOT EXISTS `PlayerMedicalStaffAssociation` (
  `PlayerID` INT NOT NULL,
  `Medical StaffID` INT NOT NULL,
  INDEX `PlayerID_idx` (`PlayerID` ASC) VISIBLE,
  INDEX `Medical StaffID_idx` (`Medical StaffID` ASC) VISIBLE,
    FOREIGN KEY (`PlayerID`)
    REFERENCES `Player` (`PlayerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Medical StaffID`
    FOREIGN KEY (`Medical StaffID`)
    REFERENCES `Medical Staff` (`Medical StaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayerScoutAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayerScoutAssociation` ;

CREATE TABLE IF NOT EXISTS `PlayerScoutAssociation` (
  `PlayerID` INT NOT NULL,
  `Scout ID` INT NOT NULL,
  INDEX `PlayerID_idx` (`PlayerID` ASC) VISIBLE,
  INDEX `ScoutID_idx` (`Scout ID` ASC) VISIBLE,
    FOREIGN KEY (`PlayerID`)
    REFERENCES `Player` (`PlayerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ScoutID`
    FOREIGN KEY (`Scout ID`)
    REFERENCES `Scout` (`ScoutID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayerTeamAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayerTeamAssociation` ;

CREATE TABLE IF NOT EXISTS `PlayerTeamAssociation` (
  `PlayerID` INT NOT NULL,
  `TeamID` INT NOT NULL,
  INDEX `PlayerID_idx` (`PlayerID` ASC) VISIBLE,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
    FOREIGN KEY (`PlayerID`)
    REFERENCES `Player` (`PlayerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TeamID`
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game` ;

CREATE TABLE IF NOT EXISTS `Game` (
  `GameID` INT NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(45) NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Time` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GameID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameTeamAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameTeamAssociation` ;

CREATE TABLE IF NOT EXISTS `GameTeamAssociation` (
  `GameID` INT NOT NULL,
  `TeamiD` INT NOT NULL,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
  INDEX `TeamID_idx` (`TeamiD` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`TeamiD`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameFan/UserWatchingtheGameAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameFan/UserWatchingtheGameAssociation` ;

CREATE TABLE IF NOT EXISTS `GameFan/UserWatchingtheGameAssociation` (
  `GameID` INT NOT NULL,
  `FanID` INT NOT NULL,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
  INDEX `FanID_idx` (`FanID` ASC) VISIBLE,
  CONSTRAINT `GameID`
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FanID`
    FOREIGN KEY (`FanID`)
    REFERENCES `Fan/User Watching the Game` (`FanID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameGameStatisticsProviderAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameGameStatisticsProviderAssociation` ;

CREATE TABLE IF NOT EXISTS `GameGameStatisticsProviderAssociation` (
  `GameID` INT NOT NULL,
  `ProviderID` INT NOT NULL,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
  INDEX `ProviderID_idx` (`ProviderID` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProviderID`
    FOREIGN KEY (`ProviderID`)
    REFERENCES `Game Statistics Provider` (`ProviderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameMerchandiseManagerAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameMerchandiseManagerAssociation` ;

CREATE TABLE IF NOT EXISTS `GameMerchandiseManagerAssociation` (
  `GameID` INT NOT NULL,
  `MerchManagerID` INT NOT NULL,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
  INDEX `MerchManagerID_idx` (`MerchManagerID` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MerchManagerID`
    FOREIGN KEY (`MerchManagerID`)
    REFERENCES `Merchandise Manager` (`MerchManagerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameRefereeAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameRefereeAssociation` ;

CREATE TABLE IF NOT EXISTS `GameRefereeAssociation` (
  `GameID` INT NOT NULL,
  `RefereeID` INT NOT NULL,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
  INDEX `RefereeID_idx` (`RefereeID` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RefereeID`
    FOREIGN KEY (`RefereeID`)
    REFERENCES `Referee` (`RefereeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameSchedulerAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameSchedulerAssociation` ;

CREATE TABLE IF NOT EXISTS `GameSchedulerAssociation` (
  `GameID` INT NOT NULL,
  `SchedulerID` INT NOT NULL,
  INDEX `SchedulerID_idx` (`SchedulerID` ASC) VISIBLE,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SchedulerID`
    FOREIGN KEY (`SchedulerID`)
    REFERENCES `Scheduler` (`SchedulerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameFan/UserReviewingGamesAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameFan/UserReviewingGamesAssociation` ;

CREATE TABLE IF NOT EXISTS `GameFan/UserReviewingGamesAssociation` (
  `GameID` INT NOT NULL,
  `ReviewingFanID` INT NOT NULL,
  INDEX `ReviewingFanID_idx` (`ReviewingFanID` ASC) VISIBLE,
  INDEX `GameID_idx` (`GameID` ASC) VISIBLE,
    FOREIGN KEY (`GameID`)
    REFERENCES `Game` (`GameID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ReviewingFanID`
    FOREIGN KEY (`ReviewingFanID`)
    REFERENCES `Fan/User Reviewing Games` (`ReviewingFanID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamTeamStaffAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamTeamStaffAssociation` ;

CREATE TABLE IF NOT EXISTS `TeamTeamStaffAssociation` (
  `TeamID` INT NOT NULL,
  `TeamStaffID` INT NOT NULL,
  INDEX `TeamStaffID_idx` (`TeamStaffID` ASC) VISIBLE,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TeamStaffID`
    FOREIGN KEY (`TeamStaffID`)
    REFERENCES `Team Staff` (`TeamStaffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamCoachAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamCoachAssociation` ;

CREATE TABLE IF NOT EXISTS `TeamCoachAssociation` (
  `TeamID` INT NOT NULL,
  `CoachID` INT NOT NULL,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
  INDEX `CoachID_idx` (`CoachID` ASC) VISIBLE,
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CoachID`
    FOREIGN KEY (`CoachID`)
    REFERENCES `Coach` (`CoachID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamSportsLeagueOrganizerAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamSportsLeagueOrganizerAssociation` ;

CREATE TABLE IF NOT EXISTS `TeamSportsLeagueOrganizerAssociation` (
  `TeamID` INT NOT NULL,
  `OrganizerID` INT NOT NULL,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
  INDEX `OrganizerID_idx` (`OrganizerID` ASC) VISIBLE,
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`OrganizerID`)
    REFERENCES `Sports League Organizer` (`OrganizerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamSocialMediaManagerAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamSocialMediaManagerAssociation` ;

CREATE TABLE IF NOT EXISTS `TeamSocialMediaManagerAssociation` (
  `TeamID` INT NOT NULL,
  `SocialMediaManagerID` INT NOT NULL,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
  INDEX `SocialMediaManagerID_idx` (`SocialMediaManagerID` ASC) VISIBLE,
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SocialMediaManagerID`
    FOREIGN KEY (`SocialMediaManagerID`)
    REFERENCES `Social Media Manager` (`SocialMediaManagerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamFinancialOfficerAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TeamFinancialOfficerAssociation` ;

CREATE TABLE IF NOT EXISTS `TeamFinancialOfficerAssociation` (
  `TeamID` INT NOT NULL,
  `FinancialOfficerID` INT NOT NULL,
  INDEX `TeamID_idx` (`TeamID` ASC) VISIBLE,
  INDEX `FinancialOfficerID_idx` (`FinancialOfficerID` ASC) VISIBLE,
    FOREIGN KEY (`TeamID`)
    REFERENCES `Team` (`TeamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FinancialOfficerID`
    FOREIGN KEY (`FinancialOfficerID`)
    REFERENCES `Financial Officer` (`FinancialOfficerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
